version: "3.7"
services: 
 mysql:
  image: mysql:latest
  restart: always
  container_name: Full_2020_086300
  ports:
   - 3306:3306
  networks:
   BridgeZadanie1:
    ipv4_address: 10.0.10.3
  environment:
      MYSQL_ROOT_PASSWORD: "AJaczynski"
      MYSQL_DATABASE: "AJaczynski"
      MYSQL_USER: "AJaczynski"
      MYSQL_PASSWORD: "AJaczynski"
 java:
  image: verdoux/docker:latest
  container_name: AJaczynskiJava
  depends_on:
   - mysql
  networks:
   - BridgeZadanie1
  stdin_open: true
  tty: true
networks:
 BridgeZadanie1:
  driver: bridge
  ipam:
   config:
    - subnet: 10.0.10.0/24
